### ISSUE TITLE
Instantsearch hooks: router not getting along with Next.JS 

### ISSUE THREAD

**Issue by dsbrianwebster** [algolia/instantsearch#5241]
We are trying out a server rendered search implementation with NextJS. All seems okay until we try to add a routing object to InstantSearch. We are using routing to have urls for our search state, and to make them SEO friendly (q=potato&type=tuber). There are all sorts of quirks though, from additional re-renders on load to the rest of the application routing breaking. 

**1. Re-Render Example:** 
If we try starting at url `/search?q=potato` we immediately see a re-render to `/search`. 

**2. Routing Example:** 
When we click on a hit/result `<Link href={`/post/${hit.slug}`>🥔 hit</Link>` we are taken to our expected `/post/${hit.slug}` url, but then from there our routing in general seems to be broken. Clicking back moves to `/search?q=potato`, but only the url changes. Page content is not updated.

![StepBrothers_3lg copy](https://user-images.githubusercontent.com/8154653/172395533-8ac7d209-c1e2-4ba2-98c6-4bd9f063b1df.jpg)

**Comment by aymeric-giraudet** [comment]
Hi all, we are currently working on a solution, and we came up with the idea of a package that lets you create a custom router that is compatible with Next.js and fixes the back button issue as well as the dynamic routing issue.

It needs to be its own package because it has `next` as a `peerDependency` so we can use its router.

Before moving forward we'd appreciate getting your feedback. For this we released this experimental package [`instantsearch-router-next-experimental`](https://www.npmjs.com/package/instantsearch-router-next-experimental)
Please note that as its name implies, this one should only be used for testing. If the solution is validated a new packaged with a definitive name and API will get published.

To use it, install it :
```sh
yarn add instantsearch-router-next-experimental
# or if you're using npm
npm install instantsearch-router-next-experimental
```
Then you can instantiate it and pass it in the `routing` prop of the `<InstantSearch>` component :
```js
import { createInstantSearchNextRouter } from 'instantsearch-router-next-experimental';
export default function Page({ serverState, url }) {
  return (
    <InstantSearchSSRProvider {...serverState}>
      <InstantSearch
        searchClient={searchClient}
        indexName="instant_search"
        routing={{ router: createInstantSearchNextRouter({ serverUrl: url }) }}
      >
        {/* ... */}
      </InstantSearch>
    </InstantSearchSSRProvider>
  );
}
```
If you are not using SSR therefore not having a `url` prop, you can simply call `createInstantSearchNextRouter` without any argument.
And if you have custom routing methods such as `createUrl` or `parseUrl` you may pass them in the first argument as well. You can find more info about usage on the [npm page](https://www.npmjs.com/package/instantsearch-router-next-experimental)

You may find the source code in the package itself or on [this branch](https://github.com/algolia/instantsearch/tree/feat/experimental-next-router/packages/react-instantsearch-hooks-next-router).

We're looking forward to hearing how it works for you.
It can be a reaction to this comment if it works nicely for you, or a comment detailing which version of `next` and `react-instantsearch-hooks` you are using if it does not work ! 

Thanks 😁

**Comment by Raesta** [comment]
Hi @aymeric-giraudet,

thank you for your solution, but I have a problem actually.

I use :
- next : 11.0.1
- react-instantsearch-hooks-web 6.32.0

My problem is on the loading of InstantSearch
![image](https://user-images.githubusercontent.com/4834347/213226582-12332cac-873e-4d00-b034-86cf3e123d05.png)

The understanding of this problem is probably the old version of next but currently we can not migrate.

**Comment by aymeric-giraudet** [comment]
Hi @Raesta,

Thanks for the feedback ! It is very helpful for the future, looks like we relied on a pretty new method.

Can you try setting the `doNotOverrideBeforePopState` option to `true` ?
Your routing would look like this : 
```js
{
  router: createInstantSearchNextRouter({ 
    serverUrl: url,
    doNotOverrideBeforePopState: true
  }) 
}
```

Normally it should not call `beforePopState` with this, please let me know if it did :)

In the meantime I'll iterate and check if the method exists before using it and publish a newer version.

**Comment by aymeric-giraudet** [comment]
Hi @Raesta,

Sorry for the double post but it should be fixed by now, with version `0.0.5`
What I did is I added this line to `package.json` : 
```json
"exports": {
  "webpack": "./dist/index.cjs"
}
```
To instruct webpack to use `cjs` even if `mjs` is available, and it seems to fix things.

You can let me know if this fixes things on your end too, thanks ! :)

**Comment by Raesta** [comment]
@aymeric-giraudet work perfectly, thanks a lot for your work.

When do you think the final package will be published?

**Comment by colis** [comment]
Hi @aymeric-giraudet, and thanks for the update.

I'm using `next 13.0.6` and `react-instantsearch-hooks 6.38.3` (CSR-only), unfortunately I'm still seeing the re-render issue mentioned in the first post.

**Comment by Haroenv** [comment]
@colis, please create a reproduction for that issue? I believe you may possibly not be rendering a SearchBox, which is required for the parameters to stay in the URL.

**Comment by colis** [comment]
hi @Haroenv, I do use the SearchBox, along with various RefinementList components

**Comment by aymeric-giraudet** [comment]
@Raesta : we want to gather as much feedback as possible to make sure it covers most issues and versions, so it should come out in around 1 month from now

@colis : I can't seem to reproduce the issue on my end, there might be some specific routing ? A reproduction of the issue on codesandbox would help greatly

**Comment by avremel** [comment]
@aymeric-giraudet Thank you for the package!

I've noticed that `windowTitle` doesn't seem to work. It flashes the new title for a second and then reverts back to the old one.

[Live demo](https://frontend.ajmadison.com/c/): Select a color and observe the title.

I've provided custom routing functions:

```js
 routing: {
      router: createInstantSearchNextRouter({
        serverUrl,
        routerOptions: {
          windowTitle: (routeState) => windowTitle(routeState, facetConfig),
          createURL,
          parseURL,
        },
      }),
      stateMapping: {
        routeToState: (params) => routeToState(params, facetConfig),
        stateToRoute,
      },
    }
```

**Comment by aymeric-giraudet** [comment]
Hi @avremel,

Are you using the [`<Head>` component from `next/head`](https://nextjs.org/docs/api-reference/next/head) ?
This overrides the title when rerendered, maybe that could be it ?

Otherwise I did some debugging on my side, I see that `windowTitle` runs twice but with the same `routeState`, maybe something in `facetConfig` changes in between ?

**Comment by avremel** [comment]
@aymeric-giraudet 

We are using `<Head>` but the problem persists even if I remove `<title>` from Head. Maybe I need to remove Head entirely?

`facetConfig` doesn't change between renders. It is an server side API call response.

**Comment by aymeric-giraudet** [comment]
@avremel 

Even if you don't put a `<title>` tag in `<Head>` it does override with an empty value when router's `push` is called :/

For now I would suggest either removing `Head` completely if you can, otherwise with `useRef` you can store the created title in `windowTitle` and use it as a child for `<Head><title>...</title></Head>`

I'll look for other solutions for the definitive package :)

**Comment by osseonews** [comment]
Thanks for the great thread. We are on Next 13 and React 18 and have 6.38.3 of instasearch hooks. We still have the back button issue mentioned above. 

Two quick questions: 

1. Is this fixed in the instantsearch-router-next-experimental package? 

2. Also, my quick fix is to just use standard 'a href' on the Search page, instead of Next Link component to link to the content. This reloads the page and everything works fine. What is wrong with this approach? I mean I understand you lose some benefits by not having the Link component in search, but at least everything works and it's just the search page. We can use Link elsewhere on the site.  I really haven't seen any difference in speed or usability using classic "a href" to link to content from the search. So I'm curious if this is a reasonable solution if we don't care about Link component on search?

**Comment by Raesta** [comment]
@aymeric-giraudet ok i have a strange behaviour

I search a word, apply filter in list & I click on the button which will mount a component with the instantSearch which will  redirect to /search without params.

**Comment by aymeric-giraudet** [comment]
@osseonews : 
Yes this is fixed in the package ! 
Using a simple `<a>` tag does work but it beats the purpose of making Single Page Apps, for example you will lose the `algoliasearch` cache so any subsequent `back` button click will trigger a request to Algolia again.

@Raesta : 
I will need a reproduction to help please, can be a Codesandbox or a repo.
Are you using a custom `createURL` ? This normally shouldn't ever return `null`.

**Comment by colis** [comment]
@aymeric-giraudet I've been testing the package to no avail. The codebase is a bit complex and a reproduction on codesandbox might take quite some time. Is there any other way I can share the codebase with you? (it's a client's project so it's not publicly available).

In the meantime, you can see an example at this link https://mecum-auctions-develop.vercel.app/auctions/glendale-2023/lots/

On page load we initialise a RefinementList with a specific value and the URL changes accordingly. However, if you try and refresh the page, the query vars disappear from the URL and the RefinementList previously applied is removed. The same thing happens when you copy/paste the URL with the query vars or if you navigate away and then back to the search results page with the back button of the browser.

**Comment by aymeric-giraudet** [comment]
@colis : 
After some intense debugging session I found out that when reloading the page with the initial query, `removeWidgets` gets called on the `taxonomies.auction_tax.name` refinement list which makes InstantSearch cleanup the state thus resetting the query. So you have to make sure your <RefinementList> or `useRefinementList` is mounted once and not unmounted later.
It most likely doesn't have anything to do with Next.js or the router.
There's something important to know when using React InstantSearch Hooks, it's that unmounting a widget component or hook cleans up its state. Which means if you do conditional rendering you have to be very careful. There's a guide for you to know more about it : https://www.algolia.com/doc/guides/building-search-ui/widgets/show-and-hide-widgets/react-hooks/

@osseonews : 
It's coming out this month ! We'll make an announcement on this issue when it's the case :)

**Comment by wenche** [comment]
@aymeric-giraudet Thank you so much for the effort to fix this issue 👏 

Just one little thing I see when we tested this in our code base (the problem might as well be at our end, but I don't quite see why 🤔 ). To be able to better see what's going on, we have added a console.log to `onStateChange` to the InstantSearch. Like this:

```
const onStateChange = (params: any) => {
  console.log("Query", params.uiState.Data_Set_Test?.query)
  params.setUiState(params.uiState)
}

   <InstantSearch
        searchClient={isServerRendered ? searchClientServer : searchClient}
        indexName="Data_Set_Test"
        onStateChange={onStateChange}
        routing={{ router: createInstantSearchNextRouter({ serverUrl }) }}
      >
```

My Hit component is a link to a detail view. When I go back and forth between the search view and the detail view to verify that the browser back issue is now gone, I notice this in the console. Seems like the console.log statement is printed one more time for each back and forth? Might indicate that something is not cleaned up? 
![Skjermbilde 2023-02-06 kl  13 50 24](https://user-images.githubusercontent.com/1568252/216975847-47c0e61e-aaba-4108-b4f9-30c582558188.png)

**Comment by LefanTan** [comment]
Thank you for fixing the issue, but `getServerState` doesn't seem to know how to handle `router` during SSR like NextJS does?

This is the errors I'm getting on everywhere that uses next/router:
```
Cannot read property 'query' of null
```

**Comment by wenche** [comment]
Unfortunately, we see some more issues when we use this new library. We have created an example repository to [highlight our findings](https://github.com/equinor/data-marketplace-algolia-test) (Let me know if you need our Algolia app id and the api key ).

Disclaimer: Some of these issues might have the same root cause, but it's not easy to find a way to explain without too much confusion. That's why I tried to split it up 😅 

**Steps to reproduce issue #1**
1. On the front page, we have a client side link with an initial query param added. `?Data_Set%5Bquery%5D=data` Click this link named `Take me to the search!`
2. Server side everything seems to be OK, but then some client side code kicks in, removes the initial query param and pushes this to the router state so that the search state is changed to the empty search 
3. The correct state is pushed to the router history, so on browser back everything works as expected

**Steps to reproduce issue #2**
1. Go to the search page with an empty search
2. Hard refresh the page (cmd+r)
3. Choose a filter/type something in the search box
4. Some client side code will reset the search state, and we see `The UI state for the index "Data_Set" is not consistent with the widgets mounted.` warning in the console

**Steps to reproduce issue #3**
1. Go to the search page
2. Search for something, like `data`
3. Go to the detail page for a hit
4. Go back to the search page using browser back
5. Server side everything is fine, but then some client side code will reset the search state

**Plot twist**
If we use the `onStateChange` function, issue #1 and #3 seems to work.

**Comment by sbkl** [comment]
@aymeric-giraudet Works perfectly for my use case and just pushed it to production :)

**Comment by wenche** [comment]
@aymeric-giraudet  Thank you for your reply. I can confirm that things seems to work fine without `reactStrictMode`. 👍 However, I really hope that you are able to fix this as we don't see it as a good long term solution to disable this as we want our code base to work properly especially with React 18's new behaviour for useEffect locally 😃  But it's fine for a short amount of time to disable this. 

Might also be an idea to highlight this gotcha in the package's README since it's strongly suggested to enable this flag and for example create-next-app enables this by default. 

Looking forward to the final release of this package as it solves on of our main issues with using Algolia and Next  🙌

**Comment by aymeric-giraudet** [comment]
Hi @wenche, thanks again for the replies !
I totally agree, we'll further iterate on how `InstantSearch` cleans up after unmounting, as this problem could impact other middlewares as well. It should be good by the time the official package is released :)

**Comment by FaroukMekk** [comment]
When using the back button from a page not using InstantSearch to my InstantSearch page, every facet is removed from the url (and from the state). Is it the expected behavior ?

**Comment by adesege** [comment]
Doesn't seem to work well with dynamic paths.

**Comment by Haroenv** [comment]
@adesege do you have a reproduction? the example in the repo is using a dynamic path

**Comment by adesege** [comment]
@dhayab's fix works for me.

My use case requires using one of the facets as a path param. However, using instantsearch-router-next-experimental did not properly re-render the next page when the facet is selected.

**Comment by aymeric-giraudet** [comment]
Hi @adesege, do you mean that when you click on a `<Link>` from `next/link` that goes to the same dynamic route (e.g. `/search/[category]`), `InstantSearch` is not aware of the URL change ? 
Normally it should and that's one of the issues we meant to address, although ideally you should use `InstantSearch`'s `refine` functions to change state.
Could you please send a link to a reproduction ? It would be very helpful for us to make the best solution. Thanks !

**Comment by franciskodama** [comment]
@aymeric-giraudet

First of all, thank you, and congratulations on the work here. It's great to know that we can count on people like you here. :)

I know you replied to osseonews that the **BACK BUTTON ISSUE** was resolved in this package, however, in our project, this problem persists.

- In our project, we have a product listing page like any e-commerce.
- If the user goes to page 2 of one of the categories of this list of products (../us/s/women/clothing/dresses?products%5Bpage%5D=2), then clicks on one of the products, and clicks on the browser's back button afterward, he/she goes back to page 1 (../us/s/women/clothing/dresses).

From what I've read here, what's happening in our project is the same as in other people's reports.
_"Clicking back moves to /search?q=potato, but only the url changes. Page content is not updated."_

So, I'm curious to know if you're still receiving reports of this Back Button Issue or if you're aware that the problem might still exist. 
PS.: Of course, we know that the problem could be on our end.

Also, do you have any predictions as to when the official production use package will be released? We're eagerly waiting for it, and any information you could provide would be greatly appreciated!

Thanks!

**Comment by Haroenv** [comment]
The production package has been released, but not yet announced as we didn't finish the documentation. In the mean time you can use the package already: https://www.npmjs.com/package/react-instantsearch-hooks-router-nextjs

We're not aware of any further issues relating to the back button, so please create a reproduction so we can debug it.

**Comment by aymeric-giraudet** [comment]
Hi @franciskodama,

You can also check out this CodeSandbox that shows the router in action : https://codesandbox.io/s/github/algolia/instantsearch/tree/master/examples/react-hooks/next-routing

Even by adding a `<Pagination>` component and clicking on the next page then on the link in `<Hits>`, pressing the back button does work. 
You can see before going on the article page that if you type `window.history.state` in the console you have a Next router history state. Which kind of state do you have on your app before navigating ? Do you have a custom `<Pagination>` component that handles navigation by itself ?

**Comment by JugglerX** [comment]
@franciskodama I have the same problem with the back button after updating to `"react-instantsearch-hooks-web": "^6.40.0"`

> So, I'm curious to know if you're still receiving reports of this Back Button Issue or if you're aware that the problem might still exist.

**Comment by mikkio-j** [comment]
@franciskodama @JugglerX have similar problem currently with `react-instantsearch-hooks-router-nextjs`.

1. Going on listing page and adding a filter. e.g. `women?color=black`
2. Navigating to different subcategory e.g `/women/jackets/`
3. Hitting back button, url changes, moment later the content changes, and filters are cleared: `women?color=black -> /women/`

**Comment by franciskodama** [comment]
Hey everyone!
@JugglerX, @mikkio-j 

Sorry for the delay in getting back to you. We're still trying to figure out what's going on, but it seems like the package that Haroenv mentioned above is working well. We realized that the issue is something on our end and we still don't have a solution for that.

I just wanted to take a moment to thank all of you for your help, @aymeric-giraudet, and @Haroenv. Your assistance has been much appreciated!

**Comment by Haroenv** [comment]
@mikkio-j, @JugglerX, @franciskodama, does any of you have a reproduction of this issue?

**Comment by aymeric-giraudet** [comment]
@JugglerX : 
Did you also install `react-instantsearch-hooks-router-nextjs` and created a new router with `createInstantSearchRouterNext` that you passed to `routing` ? Just updating `react-instantsearch-hooks` to the latest version doesn't fix it.

@mikkio-j , @franciskodama : 
What happens if you select a refinement and refresh the page with F5/Cmd+R ? Does the URL get cleared too ? Or is it only when going back/forward ? A reproduction would help indeed :)

**Comment by DB-Alex** [comment]
package.json:

```
        "react-instantsearch-hooks-server": "^6.40.0",
        "react-instantsearch-hooks-web": "^6.40.0",
        "react-instantsearch-hooks-router-nextjs": "^6.40.0",
```

Everything works as expected until we start using sorting. As soon as we use sorting and hit a product the browser back button does not work anymore. Filtering works as expected.

**Comment by aymeric-giraudet** [comment]
Hi @DB-Alex,

May you send a reproduction please ?
I tried adding a `SortBy` in our example and it works as expected : https://codesandbox.io/s/vigorous-shockley-gkvw1r?file=/pages/index.tsx
If you sort by price, click on a hit and then press the back button it does work.

**Comment by aymeric-giraudet** [comment]
Hi @mikkio-j,

I've seen a ticket you've raised to our support and checked, it's not due to routing really, it's the way Next.js, React and InstantSearch work.
You can see the issue is not just when pressing the back button but also on reload and when clicking on the links (e.g. from `category/women/socks` to `category/women?color=blue` it doesn't work either)
- To fix for reload it's because you're not passing `blocks` to your component in `getServerState`.
- For the back button and link clicks removing filters, it's because at this point it's doing CSR and keeping the same `InstantSearch` instance across navigation, and since you're using new keys, your `useRefinementList` hooks get unmounted and clear the state. A quick way to fix it would be to force remounting InstantSearch by setting `key={url}` in `InstantSearchSSRProvider`.
I'll send back a fork of your CodeSandbox with the solution to customer support as it might be private for you :)

P.S : Overall maybe this could be avoided by relying on `refine` functions from our hooks rather than Next.js `Link` I think

**Comment by aymeric-giraudet** [comment]
Hi everyone ! 🙋‍♂️

First of all, thank you for your patience and for providing precious feedback.

Our solution for creating a Next.js compatible router for InstantSearch is now generally available and published on npm as [`react-instantsearch-hooks-router-nextjs`](https://www.npmjs.com/package/react-instantsearch-hooks-router-nextjs).

Its documentation is available on the Algolia docs right there : https://www.algolia.com/doc/api-reference/widgets/instantsearch-next-router/react-hooks/

You can also see it in action on CodeSandbox : https://codesandbox.io/s/github/algolia/instantsearch/tree/master/examples/react-hooks/next-routing

If you're seeing any problem still, please __raise another issue with a reproduction__ and make sure to check that it's not just related to back button press, try to see if reloading the page raises the same issue. If you're also on a dynamic route, check that the issue is not caused by components/hooks being unmounted.

Thanks again to all of you !

**Comment by DB-Alex** [comment]
> Hi @DB-Alex,
> 
> May you send a reproduction please ? I tried adding a `SortBy` in our example and it works as expected : https://codesandbox.io/s/vigorous-shockley-gkvw1r?file=/pages/index.tsx If you sort by price, click on a hit and then press the back button it does work.

This was resolved by adding a key to the SSRProvider:

```
<InstantSearchSSRProvider
	{...serverState}
	key={router.asPath}
>
```

**Comment by JugglerX** [comment]
@aymeric-giraudet Thank you for working so hard on a fix for this issue. I wanted to provide an update on my solution.

The problem for me seemed to be that my `<Layout/>` component was unmounting between routes. 

Here is some more detail as It might help others:

I needed to add the new package `react-instantsearch-hooks-router-nextjs` and implement it as per the docs. https://www.algolia.com/doc/api-reference/widgets/instantsearch-next-router/react-hooks/

I was able to get a working version with a basic new Nextjs site. But when I installed the above on my existing site the back button issue continued to occur. 

Stripping back my Nextjs site, the issue was resolved when I removed the layout component that wrapping each page. I modified my layout architecture to that suggested in the Nextjs docs here https://nextjs.org/docs/basic-features/layouts#per-page-layouts

**Comment by kblizeck** [comment]
@aymeric-giraudet Installed the new package and it works great with refinement, menus, clicking through to a Hit and then using the back button. However, I was previously sending url parameters to pre-set search and Menu and those are being cleared from the URL and not applied to the InstantSearch state. Any suggestions on how to tackle pre-defined url parameters?

Steps to issue:
- User is on a listing of categories
- Clicks a category and is sent to the InstantSearch component with url = http://localhost:3000/search?document_search%5Bmenu%5D%5Bdomain%5D=Cloud+Security
- URL query parameters are cleared and not applied
- Previously, with just `routing={true}`, the URL parameters passed were respected and triggered a search

**Comment by Haroenv** [comment]
@kblizeck, could you create a reproduction and a new issue please?

**Comment by aymeric-giraudet** [comment]
Hi everyone ! 🙌

I'm sorry but I will have to lock the issue so that people don't have to scroll up to find the solution.

Our solution for creating a Next.js compatible router for InstantSearch is now generally available and published on npm as [react-instantsearch-hooks-router-nextjs](https://www.npmjs.com/package/react-instantsearch-hooks-router-nextjs). It has to be a separate package as it has next as a peerDependency.

Its documentation is available on the Algolia docs right there : https://www.algolia.com/doc/api-reference/widgets/instantsearch-next-router/react-hooks/

You can also see it in action on CodeSandbox : https://codesandbox.io/s/github/algolia/instantsearch/tree/master/examples/react-hooks/next-routing

If you're seeing any problem still, please [**raise another issue with a reproduction**](https://github.com/algolia/instantsearch.js/issues/new?template=BUG_REPORT.yml&labels=triage,Library%3A%20React+InstantSearch+Hooks).

Thanks again to all of you !
